import { UserProvider } from "@/components/user-provider";
import { getUser } from "@/lib/fetchers";
import { type ReactNode } from "react";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AppLayout({ children }: { children: ReactNode }) {
  const user = await getUser();

  return <UserProvider user={user}>{children}</UserProvider>;
}
